ARG IMAGE
FROM $IMAGE

ENV DEBIAN_FRONTEND=noninteractive
ENV USER root

RUN apt-get update && apt-get -y install bash

COPY package/depends.sh /tmp/depends.sh
COPY package/common.sh /tmp/common.sh

# build depends
RUN mkdir -p /log && \
    bash /tmp/depends.sh

COPY xen /build-xen

COPY package/configure-xen.sh /build-xen/configure-xen.sh
copy package/common.sh /build-xen/common.sh

WORKDIR /build-xen

RUN chmod +x configure-xen.sh && \
    ./configure-xen.sh && \
    echo "Building Xen, this may take a few minutes..." && \
    echo CONFIG_EXPERT=y > xen/.config && \
    echo CONFIG_MEM_SHARING=y >> xen/.config && \
    make -C xen olddefconfig && \
    echo "Running Xen's make dist..." && \
    make -j$(nproc) dist-xen && \
    make -j$(nproc) dist-tools && \
    echo "Install Xen..." && \
    make -j$(nproc) install-xen && \
    make -j$(nproc) install-tools && \
    mv /build-xen/dist/install /dist-xen && \
    rm -rf /build-xen
