ARG IMAGE
ARG KFX_DIR

FROM xen-intermediate

COPY $KFX_DIR /build

RUN cd /build/dwarf2json && \
    /usr/local/go/bin/go build

ENV INSTALL_PATH=/build/usr

WORKDIR /build/libvmi

RUN autoreconf -vif && \
    ./configure --prefix=$INSTALL_PATH --disable-kvm --disable-bareflank --disable-file && \
    make -j$(nproc) && \
    make install && \
    ldconfig
    
WORKDIR /build/capstone

RUN mkdir build && cd build && \
    cmake .. && \
    make && \
    make prefix=$INSTALL_PATH install && \
    ldconfig
    

RUN export INSTALL_PATH="/build/usr" && \
    cd /build/libxdc && \
    make prefix=$INSTALL_PATH install
    

RUN export INSTALL_PATH="/build/usr" && \
    cd /build && \
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$INSTALL_PATH/lib" && \
    export C_INCLUDE_PATH="$INSTALL_PATH/include" && \
    export CPLUS_INCLUDE_PATH="$INSTALL_PATH/include" && \
    export PKG_CONFIG_PATH="$INSTALL_PATH/lib/pkgconfig/" && \
    export LDFLAGS="-L$INSTALL_PATH/lib" && \
    export CFLAGS="-I$INSTALL_PATH/include" && \
    autoreconf -vif && \
    ./configure --prefix=$INSTALL_PATH && \
    make -j$(nproc) && \
    make  install

WORKDIR /build
RUN chmod +x package/*.sh

CMD ["./package/mkdeb.sh", "$IMAGE"]
